package com.example.eparkprogram.ui.admin

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ReportsScreen(navController: NavController) {

    var startDate by remember { mutableStateOf("01/05/2026") }
    var endDate by remember { mutableStateOf("29/05/2026") }
    var reportGenerated by remember { mutableStateOf(false) }

    val reportData = listOf(
        Triple("Zona A - Centro", 842, "₡421.000"),
        Triple("Zona B - Plaza", 634, "₡253.600"),
        Triple("Zona C - Mercado", 1205, "₡421.750"),
        Triple("Zona D - Parque", 312, "₡93.600"),
        Triple("Zona E - Hospital", 756, "₡340.200")
    )

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Reportes") },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.Filled.ArrowBack, contentDescription = "Atrás")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color(0xFF1565C0),
                    titleContentColor = Color.White,
                    navigationIconContentColor = Color.White
                )
            )
        }
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Selector de fechas
            Text("Rango de fechas", fontWeight = FontWeight.Bold, fontSize = 16.sp)

            Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                OutlinedTextField(
                    value = startDate,
                    onValueChange = { startDate = it },
                    label = { Text("Desde") },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    singleLine = true,
                    leadingIcon = {
                        Icon(Icons.Filled.CalendarToday, contentDescription = null, modifier = Modifier.size(18.dp))
                    }
                )
                OutlinedTextField(
                    value = endDate,
                    onValueChange = { endDate = it },
                    label = { Text("Hasta") },
                    modifier = Modifier.weight(1f),
                    shape = RoundedCornerShape(12.dp),
                    singleLine = true,
                    leadingIcon = {
                        Icon(Icons.Filled.CalendarToday, contentDescription = null, modifier = Modifier.size(18.dp))
                    }
                )
            }

            Button(
                onClick = { reportGenerated = true },
                modifier = Modifier.fillMaxWidth().height(48.dp),
                shape = RoundedCornerShape(12.dp),
                colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF1565C0))
            ) {
                Icon(Icons.Filled.Search, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Consultar reporte")
            }

            if (reportGenerated) {
                // Resumen general
                Text("Resumen del período", fontWeight = FontWeight.Bold, fontSize = 16.sp)

                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    listOf(
                        Triple("Total sesiones", "3.749", Color(0xFF1565C0)),
                        Triple("Ingresos totales", "₡1.530.150", Color(0xFF2E7D32)),
                        Triple("Multas emitidas", "147", Color(0xFFE53935))
                    ).forEach { (label, value, color) ->
                        Card(
                            modifier = Modifier.weight(1f),
                            shape = RoundedCornerShape(12.dp),
                            elevation = CardDefaults.cardElevation(2.dp)
                        ) {
                            Column(
                                modifier = Modifier.padding(12.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                Text(value, fontWeight = FontWeight.Bold, fontSize = 14.sp, color = color)
                                Text(label, fontSize = 10.sp, color = Color.Gray)
                            }
                        }
                    }
                }

                // Desglose por zona
                Text("Ingresos por zona", fontWeight = FontWeight.Bold, fontSize = 16.sp)

                Card(
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(16.dp),
                    elevation = CardDefaults.cardElevation(2.dp)
                ) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        reportData.forEachIndexed { index, (zone, sessions, income) ->
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Column(modifier = Modifier.weight(1f)) {
                                    Text(zone, fontWeight = FontWeight.Medium, fontSize = 13.sp)
                                    Text("$sessions sesiones", fontSize = 12.sp, color = Color.Gray)
                                }
                                Text(income, fontWeight = FontWeight.Bold, color = Color(0xFF2E7D32))
                            }
                            if (index < reportData.size - 1)
                                Divider(modifier = Modifier.padding(vertical = 8.dp))
                        }
                    }
                }
            }
        }
    }
}